### ISSUE TITLE
handleUncaughtExceptions passed to Cucumberjs

### ISSUE THREAD

**Issue by cuongnguyen2190** [rochejul/gulp-angular-protractor#10]
Hi,

I got problem when I use Protractor + CucumberJS. If I execute my test via cli and get exceptions, protractor will stop and does not execute the remaining scenario. I found the runner.js inside this plugin has this line:

require('source-map-support').install();

When I changed this to: 

require('source-map-support').install({
      handleUncaughtExceptions: false
  });

Protractor will execute remaining scenario. Is there any way to pass this via config file instead of modifying this script directly ?

**Comment by rochejul** [comment]
Hi

This is a sub-dependecy of protractor from gulp-protractor. I haven't access directly to config / change that.

And it seems to have an active issue on the protractor module: https://github.com/angular/protractor/issues/876

Maybe you can check more on this way to find a patch ?

Many thanks

Cheers

**Comment by cuongnguyen2190** [comment]
Hello,

It seems there is no way to achieve the solution by modify the runner directly. I made research on many tickets of protractor but all of them seem not be resolved yet. So I had to modify the script directly.

Best regards,
Cuong Nguyen
