### ISSUE TITLE
debug mode doesn't seem to work with 'debug': true in gulp task options

### ISSUE THREAD

**Issue by mguthmuller** [rochejul/gulp-angular-protractor#11]
Hi,

I'm trying to run protractor in debug mode by setting the 'debug' option to true as explained in the documentation. Below, my protractor gulp task: 

```
gulp.task('protractor', function () {
    return gulp
      .src(['src/test/**/*_e2e.js'])
      .pipe(g.angularProtractor({
        'configFile': 'protractor.conf.js',
        'autoStartStopServer': true,
        'args': ['--baseUrl', 'http://127.0.0.1:3000']
        'debug': true
      }))
      .on('end', function () {
        g.util.log('E2E Testing complete');
        process.exit();
      })
      .on('error', function () {
        g.util.log('E2E Tests failed');
        process.exit(1);
      });
  });
```

However, the debug mode doesn't seem to be enabled, I don't have the debug console.
If I put 'debug' directly in the args array, always in the gulp task option, it works fine...

```
gulp.task('protractor', function () {
    return gulp
      .src(['src/test/**/*_e2e.js'])
      .pipe(g.angularProtractor({
        'configFile': 'protractor.conf.js',
        'autoStartStopServer': true,
        'args': ['debug', '--baseUrl', 'http://127.0.0.1:3000']
      }))
      .on('end', function () {
        g.util.log('E2E Testing complete');
        process.exit();
      })
      .on('error', function () {
        g.util.log('E2E Tests failed');
        process.exit(1);
      });
  });
```

Npm packages versions:
├─┬ gulp-angular-protractor@0.0.6
│ ├─┬ gulp-protractor@0.0.11
│ │ └─┬ protractor@3.3.0

I use the 0.0.6 version because of an issue with the selenium webdriver.

**Comment by rochejul** [comment]
Hi,

Indeed: it seems to work only with a basic usage of protractor:
- https://github.com/rochejul/gulp-angular-protractor/blob/master/index.js#L77
- https://github.com/mllrsohn/gulp-protractor/blob/master/index.js#L40

I think I have to add the option into the gulp-stream.js file:

``` js
module.exports = function (options, webDriverUrl, debugMode) {
    var files = [],
        args = options.args || [ ];

    if (debugMode) {
        args.push('debug');
    }

    // ...
};
```

I try to fix it as soon as possible

Many thanks for your feedback

Cheers
