### ISSUE TITLE
Question - run without gulp src

### ISSUE THREAD

**Issue by Martin-Andersen** [rochejul/gulp-angular-protractor#16]
There is something that I don't understand. Protractor takes a config file with an array of suites, so why do I need to pipe spec files to it?

**Comment by rochejul** [comment]
Hi

To have a better integration with Gulp, the array of suites is passed as parameters of the protractor command. So the array of suites of the files will be ignored.

Plus, we can use the wildcards to find / exclude all our specs files

Cheers
