### ISSUE TITLE
Question - run without gulp src

### ISSUE THREAD

**Issue by Martin-Andersen** [rochejul/gulp-angular-protractor#17]
First thanks for making it a lot easier to stop and start webdriver.

I would like to use suites instead of piping src file and take full advantages of the protractor config file where I define the suites to run.

`gulp.task('e2e:local', runProtractor);

   function runProtractor(done) {
      var params = process.argv;
      var args = params.length > 3 ? [params[3], params[4]] : [];

```
  gutil.log('arguments: ' + args);

gulp.src(paths.e2eSuites.itProject)
  .pipe(protractor({
      configFile: 'protractor.local.conf.js',
      args: args,
      'autoStartStopServer': true,
      'debug': false
  }))
  .on('error', function (err) {
      gutil.log(gutil.colors.red('error: ' + err));
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
  })
  .on('end', function () {
      // Close browser sync server
      browserSync.exit();
      done();
  });
```

}`

I have removed suites from the protractor.config file and using them as input to gulp src. This make the tests work.

Is this the road to take or is there a better way?

**Comment by rochejul** [comment]
This is the right way yes

Cheers
