### ISSUE TITLE
Is it posible to hide the selenium-server output?

### ISSUE THREAD

**Issue by KevinBeckers** [rochejul/gulp-angular-protractor#18]
Is it posible to hide the selenium-server output?

**Comment by rochejul** [comment]
Hi,

Maybe you can use the gulp option "--silent" ?

Or this is only the selenium-server output only to want to disable ?

If so, it needs an option

Cheers

**Comment by KevinBeckers** [comment]
Hay, 

Yes I like to disable the selenium output. Its basically every time te same.

Thanks

**Comment by rochejul** [comment]
Maybe we can have a cerbose mode

Cheers
