### ISSUE TITLE
Mobile Support Appium Start Stop 

### ISSUE THREAD

**Issue by rahulmr** [rochejul/gulp-angular-protractor#22]
Hello Julien,

Is it possible to support appium start stop using `gulp-angular-protractor`?
Please check the [link](https://github.com/angular/webdriver-manager/blob/master/mobile.md) where webdriver-manager supports mobile.

Please suggest how this can be implemented.
Thanks in advance.

**Comment by rochejul** [comment]
Hi,

It seems I need some refactoring, and to not use anymore gulp-protractor, because this one is very limited around the webdriver update instructions:

```
var webdriver_update = function(opts, cb) {
    var callback = (cb ? cb : opts);
    var options = (cb ? opts : null);
    var args = ["update", "--standalone"];
    if (options) {
        if (options.browsers) {
            options.browsers.forEach(function(element, index, array) {
                args.push("--" + element);
            });
        }
    }
    child_process.spawn(path.resolve(getProtractorDir() + '/webdriver-manager'+winExt), args, {
        stdio: 'inherit'
    }).once('close', callback);
};
```

Where we need to raise some instructions like so:

```
webdriver-manager update --android --android-api-levels 23 --android-abis armeabi-v7a
```

So I will create an experimental branch as soon as possible and try to check if it works

Thanks for your contribution

Cheers

Julien Roche

**Comment by rochejul** [comment]
I will update too the protractor version and so close the issue #24 

Cheers

**Comment by rahulmr** [comment]
Thanks a lot!

**Comment by rochejul** [comment]
Hi,

Can you try to use this branch: https://github.com/rochejul/gulp-angular-protractor/tree/experimental/appium

And so declare into your gulp file:

``` js
gulp.task('protractor', function(callback) {
    gulp
        .src(['example_spec.js'])
        .pipe(gulpProtractorAngular({
            'configFile': 'protractor.conf.js',
            'debug': false,
            'autoStartStopServer': true,
            'verbose': false,
            'webDriverUpdate': {
                'args': ['--android', '--android-api-levels', '23', '--android-abis', 'armeabi-v7a']
            }
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
});
```

Many thanks

Cheers

**Comment by rahulmr** [comment]
I am not aware how to use `npm install` for using the beta version of this package. Can I use the example present in the examples section or I will have to use my own?

**Comment by rochejul** [comment]
Simplify do:

```
npm install --save-dev https://github.com/rochejul/gulp-angular-protractor/tree/experimental/appium
```

It will declare as devDepency "gulp-angular-protractor" and download the code associated to the Git branch.

Cheers

**Comment by rochejul** [comment]
Hi

Have you got some feedbacks ?

Can I integrate the new branch ?

Many thanks
