### ISSUE TITLE
How to start webdriver manager with --ie32

### ISSUE THREAD

**Issue by vikasvoladri** [rochejul/gulp-angular-protractor#23]
I want to start webdriver-manager as 'webdriver-manager start --ie32' for running scripts in IE11 browser using 32 bit IEDriverserver.exe. 

Below is my task. Please let me know how can i implement above mechanism

gulp.task('run-ie',function(callback){
    gulp.src(['e2e/specs/LoginTestCasesSpec.js'])
        .pipe(gulpProtractorAngular({
            'configFile': './protractor.conf.js',
            'args':['--browser', 'internet explorer'],
            'autoStartStopServer': true
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
});

**Comment by rochejul** [comment]
Hi

The "args" option is only for protractor. There is no way (for the moment) to inject some parameters for webdriver.

Cheers

**Comment by vikasvoladri** [comment]
I've started webdriver-manager start --ie32 in other command prompt and set 'autoStartStopServer': false
 and ran above task, then I'm getting below mentioned error:

H:\Project4\Simple Repo\automation>gulp run-ie
[17:48:00] Using gulpfile H:\Project4\Simple Repo\automation\gulpfile.js
[17:48:00] Starting 'run-ie'...
[17:48:00] gulp-angular-protractor - The plugin is retrieved and will start soon
[17:48:00] gulp-angular-protractor - Basic use (as the gulp-protractor plugin).
'H:\Project4\Simple' is not recognized as an internal or external command,
operable program or batch file.
{ [Error: protractor exited with code 1]
  message: 'protractor exited with code 1',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-protractor',
  __safety: { toString: [Function: bound ] } }

Do i need to configure anything else?
