### ISSUE TITLE
Is it possible to use the latest version of gulp-protractor which is 3.0.0?

### ISSUE THREAD

**Issue by rahulmr** [rochejul/gulp-angular-protractor#24]
Hi Julien,
Currently, gulp-angular-protractor is using gulp-protractor 2.1.0 as I can see in the package.json, is it possible to update it to gulp-protractor 3.0.0?
I want to use protractor latest version 4.0.3.
Thanks in advance for your help.

**Comment by rochejul** [comment]
Hi,

In fact, with the issue #22 , I will not use anymore gulp-protactor as dependency but protractor direclty.

So, I will close this issue when the issue #22 will be closed

Many thanks for your feedback

Cheers

**Comment by rahulmr** [comment]
Thanks
