### ISSUE TITLE
Support for protractor-flake

### ISSUE THREAD

**Issue by wwjhu** [rochejul/gulp-angular-protractor#25]
It would be useful to be able to use protractor-flake (https://github.com/NickTomlin/protractor-flake) instead of using protractor directly. Right now protractor is hard coded. If you agree this is useful, can you indicate what the config / implementation should look like. I may be able to create PR for this.

**Comment by rochejul** [comment]
Hi

I don't know protractor-flake: what is the goal of this module ?

If you provide a pull-request, this is a good idea :)

Many thanks

**Comment by rochejul** [comment]
Hi,

I don't know protractor-flake: what is the goal of this module ?

If you provide a pull request, this is a good idea :)

Many thanks
