### ISSUE TITLE
Fails with chrome 54

### ISSUE THREAD

**Issue by AlexSwensen** [rochejul/gulp-angular-protractor#26]
Fails due to upstream dependencies being out of date.

**Comment by nalbion** [comment]
I think this is related - http://stackoverflow.com/questions/40019066/webdrivererror-connection-refused

**Comment by nalbion** [comment]
I have executed

```
$ webdriver-manager --out_dir /tmp update
...
$ webdriver-manager --out_dir /tmp status
[17:31:14] I/status - selenium standalone versions available: 2.52.0, 2.53.1 [default]
[17:31:14] I/status - chromedriver version available: 2.24 [default]
[17:31:14] I/status - geckodriver version available: v0.9.0 [default]
[17:31:14] I/status - android-sdk is not present
[17:31:14] I/status - appium is not present
```

but gulp-angular-protractor still has 2.20 (it needs to be 2.24 for Chrome 54):

```
$ my-project/node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/selenium/chromedriver --version

ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
```

If you edit `node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/config.json` and set `"chromedriver": "2.24"` and then run 

```
$ node_modules/gulp-angular-protractor/node_modules/gulp-protractor/node_modules/protractor/bin update
```

You'll have your gulp tasks up and running again, but all of my scenarios are failing:

> isElementPresent error Timed out waiting for Protractor to synchronize with the page after 30 seconds. Please see https://github.com/angular/protractor/blob/master/docs/faq.md

**Comment by rochejul** [comment]
Hi

Have you retry to update the google webdriver since ?

Otherwise, I will try to update the protractor dependecy

Cheers

**Comment by nalbion** [comment]
@rochejul if you bump to `"gulp-protractor": "3.0.0",` (I had to delete node-modules and shrink-wrap) webdriver is automatically updated and the task runs, but I'm still getting `isElementPresent error { [ScriptTimeoutError: Timed out waiting for Protractor to synchronize with the page after 30 seconds`

**Comment by nalbion** [comment]
...then again, in #24 you say that you're migrating away from gulp-protractor

**Comment by rochejul** [comment]
Hi @nalbion 
Can you check if on the feature branch "experimental/appium" the issue is fixed please ?

If so, I will integrate it as soon as possible

Many thanks

Regards

**Comment by Janens** [comment]
From what I can see "experimental/appium" uses protractor 4.0.3 which still uses chromedriver 2.22. Bumping protractor to 4.0.9 in the "experimental/appium" branch seems to fix it though.

**Comment by rochejul** [comment]
Many thank for your feedback !

I will update this branch asap and integrate it into the master branch

Regards

**Comment by rochejul** [comment]
I will publish it tonight on the npm registry

Regards

**Comment by Janens** [comment]
Confirmed that issue is fixed with version 0.2.0. Great work! :)

**Comment by rochejul** [comment]
@Janens great ! Many thanks

**Comment by AlexSwensen** [comment]
Works for me as well. Many thanks!
