### ISSUE TITLE
How to pass multiCapabilities from gulp-angular-protractor

### ISSUE THREAD

**Issue by Milan-kumar** [rochejul/gulp-angular-protractor#31]
Hi,

I need to pass multiCapabilities from gulp-angular-protractor.
Following is my requirement:
 multiCapabilities: [
         {
         browserName : 'internet explorer',
          seleniumAddress: 'http://localhost:4444/wd/hub'         
         },
        {
            browserName : 'chrome',
            seleniumAddress: 'http://172.23.230.198:4444/wd/hub'           
        }

I tried following but its throwing error
gulp.src([])
        .pipe(gulpProtractorAngular({
            'configFile': './conf.js',
            'debug': true,
            'autoStartStopServer': false,
            args: [
                '--specs', './testExecution/UserManagement/Login/*.js',
                '--multiCapabilities.0.browserName', 'internet explorer',
                '--multiCapabilities.1.browserName', 'chrome'
],
            keepAlive: true
        }))
        .on('error', function (e) {
            console.log("specs: " + specs);
            console.log(e);
            process.exit(1);
            return new gutil.PluginError("ERROR", "Error", {showStack: true});
        })
        .on('end', function (){           
        });

**Comment by guan01** [comment]
I use a little different approach and works for me, perhaps you can give this a try on your side...


    baseUrl: 'http://localhost:3000',
    specs: ['dist/**/*.feature'],
    directConnect: true,
    exclude: [],
    maxSessions: 4,
    multiCapabilities: [{
        browserName: 'internet explorer',
    },
    {
        browserName: 'MicrosoftEdge',
    },
    {
        browserName: 'chrome',
    },
    {
        browserName: 'firefox',
        marionette: true,
        directConnect: true,
    }
    ],

.....

**Comment by Milan-kumar** [comment]
@guan01 Thanks for your response.
Yes that works fine, but my requirement was to pass multiCapabilities as an argument using gulp-angular-protractor.
We need to update cli.js file https://github.com/angular/protractor/pull/1083/files  and then you can pass it as an argument:
gulp.src([])
.pipe(gulpProtractorAngular({
'configFile': './conf.js',
'debug': true,
'autoStartStopServer': false,
args: [
'--specs', './testExecution/UserManagement/Login/*.js',
'--multiCapabilities.0.browserName', 'internet explorer',
'--multiCapabilities.1.browserName', 'chrome'
],

**Comment by rochejul** [comment]
Hi @Milan-kumar 

Do you know which version of protractor allow to set the multiCapabilities option as CLI parameter ?

Currently, we used the 4.0.11 version: https://github.com/rochejul/gulp-angular-protractor/blob/master/package.json#L38

Maybe it resolve your issue ?

**Comment by Milan-kumar** [comment]
Hi @rochejul,

I am not sure and couldn't find any version of protractor that allows to set the multiCapabilities option as CLI parameter.
I am using protractor@2.5.1,  just modified cli.js as mentioned above and added following:

`if(argv.multiCapabilities) {
   var multiCapabilitiesArray = [];
   for (var i = 0; i < Object.keys(argv.multiCapabilities).length; i++) {
     multiCapabilitiesArray[i] = flattenObject(argv.multiCapabilities[i]);
   }
   argv.multiCapabilities = multiCapabilitiesArray;
 }` 

and it worked for me.

Let me know if you have any better solution or any version having multiCapabilities cli option
