### ISSUE TITLE
Updating protractor version

### ISSUE THREAD

**Issue by mribichich** [rochejul/gulp-angular-protractor#36]
Hi there, could you update the protractor version to the last one? 

Or maybe not use `protractor`  as a dependency, so everybody can use the version they want.

Or another possibility could be to allow to pass the protractor version one is using, as I've seen in others plugins, something like:

```
{
    protractor: require('protractor')
}
```

Thanks!

**Comment by rochejul** [comment]
Agreed for the option. I add it as enhancement for the next release

Regards
