### ISSUE TITLE
Selenium server is started but not executing test cases

### ISSUE THREAD

**Issue by abdul-qadir** [rochejul/gulp-angular-protractor#4]
I followed all steps and found that selenium server started while running gulp task, but it is not executing test cases. Can you let me know what can be the issue?

**Comment by rochejul** [comment]
Hi

It depends the architecture of your project and the configuration. Can you give us more feedback ? Like an example zip file ?

Thank you

**Comment by pgom** [comment]
@rochejul I had the same issue and found that on my system `WEB_DRIVER_LOG_STARTED` was different. Therefore the `callback` was not called and the process staled. Any idea why this is happening?

**Comment by rochejul** [comment]
Hi

Please look to the previous comment

Many thanks

**Comment by pgom** [comment]
JDK8 + protractor 3 on a El Capitan. The configuration file used is:

```
exports.config = {
  capabilities: {
    'browserName': 'chrome',
    'chromeOptions': {
      'args': ['disable-extensions', 'enable-crash-reporter-for-testing', 'incognito', 'start-maximized']
    }
  },
  framework: 'mocha',
  mochaOpts: {
    timeout: 35000
  },
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['./src/scripts/tests/e2e/**/*.js']
};

```

**Comment by rochejul** [comment]
Hi

Which version of Node, Gulp, this plugin are you using ?

Can you attach a sample project on you next comment (a zip file, a github repository link), to have a real case ?

Many thanks

**Comment by pgom** [comment]
@rochejul Sorry but due to some weirdness, I was not getting the last version even thought it was defined that way to be installed. Currently, the error is gone for me.

**Comment by abdul-qadir** [comment]
@rochejul node version = 0.12.5
npm version 2.11.2
I think protractor version 3.0.0 is used instead of 2.5.1 that is causing issue to me.

**Comment by rochejul** [comment]
@pgom this is a good news! Thanks!
@abdul-qadir what is the version of the gulp-angular-protractor plugin ? Do you use the last one ?

Cheers

**Comment by abdul-qadir** [comment]
@rochejul I did all setup again and use gulp-angular-protractor 0.0.6 and found following problem while run gulp task,
node version = 0.12.5
npm version 2.11.2
Error is ---->

undefined:1190
    vlog(2, () => this + ' scheduling notifications', this);

**Comment by rochejul** [comment]
@abdul-qadir Can we have the complete stacktrace ? Or a zip file with a real case ?

Because the code you have seems to be written in ES6. And I don't use it (and I think my subdependencies don't use it directly)

Many thanks

**Comment by rochejul** [comment]
Close due to not enough feedbacks
