### ISSUE TITLE
Confusion about global Protractor and node_modules Protractor

### ISSUE THREAD

**Issue by ericjames** [rochejul/gulp-angular-protractor#43]
The Protractor plugin indicates you should install protractor globally, but it appears the `gulp-angular-protractor` plugin is using its own node_module of protractor.   

So is it possible to access `webdriver-manager` CLI from that node_module?  I want to keep the webdriver open when writing tests to reduce lag time from autoStartStop. 

Command line will read from the global CLI, not the actual `gulp-angular-protractor` CLI.

**Comment by rochejul** [comment]
Related to #41 and #40

**Comment by ericjames** [comment]
I decided to alias the webdriver actually being used ie: `/node_modules/gulp-angular-protractor/node_modules/protractor.../webdriver-manager start` and it worked.  Obviously with newer npm, the directory structure is squashed.   To be honest, `npm` architecture expects your module to use its own protractor dependency, especially if a repo is deployed to other servers.
