### ISSUE TITLE
Configure for Page Object pattern project

### ISSUE THREAD

**Issue by schwarcu** [rochejul/gulp-angular-protractor#46]
How do I configure this to make it work when I have following project structure?
pages has PO files, specs has specifications files, data has files with all strings and parameters used for tests, selenium has chromeDriver etc.
![capture](https://user-images.githubusercontent.com/31127747/30166127-ad2aa3b6-93e2-11e7-8b74-866b440174cc.PNG)

**Comment by schwarcu** [comment]
My gulp file:

> 
> var angularProtractor = require('gulp-angular-protractor');
> var gulp = require('gulp');
>     gulp.task('test', function(callback) {
>         gulp
>             .src(['./**/*.js'])  -< 
>             .pipe(angularProtractor({
>                 'configFile': 'tco-conf.js',
>                 'debug': true,
>             }))
>             .on('error', function(e) {
>                 console.log(e);
>             })
>             .on('end', callback);
> 
> });

**Comment by guan01** [comment]
Not sure where to start, can you post the error when you run your test?

I have cucumber setup with this framework.
I create pageObject.ts and in my steps.ts I declare like this

var expect = require('../common/chai.js');
var homePageObj = require('../homePage/homePage-object.js');
var allSupplierObj = require('../allSuppliers/allsupplier-object.js');
var loginPageObj = require('../login/login-page-object.js');
var cartPageObj = require('../cart/cart-object.js');
var ConnectDatabase = require('../common/connectDatabase.js');
var connectDatabase = new ConnectDatabase();
var sql = 'select * from agreement_acceptance;';
var specTimeOutMS = 30000;

**Comment by guan01** [comment]
to call the obj

 loginPageObj.cartButton.click().then(function() {
});

**Comment by rochejul** [comment]
Hi

There is a bunch of examples at this link: https://github.com/rochejul/gulp-angular-protractor/tree/master/examples

Otherwise, could you make a sample of your project and attach it on the issue ? To understand what is the problem ?

Many thanks

**Comment by schwarcu** [comment]
You didn't understand my question. I have already done whole protractor project. Everything works well.
I am using directConnect, without webdriver selenium server. 
Now I want to run my protractor test as a gulp task.

After some changes now I managed to run the protractor but I only want to run specs I have defined in my protractor config which are:
`    specs: [
        "specs/pre-login-spec.js",
        "specs/login-spec.js",
        "specs/startpage-spec.js",
        "specs/topbar-spec.js",
        "specs/smallbar-spec.js",
    ],`

bug gulp runs all specs from my specs folder, and with messed up order.
How do I force gulp to run only specs defined by protractor config? or suite if I define one

**Comment by schwarcu** [comment]
I added "'autoStartStopServer': false" to skip the webdriver manager part but now I get such error:
![capture](https://user-images.githubusercontent.com/31127747/30201803-4f832f22-947c-11e7-805f-35bd573b491c.PNG)

**Comment by schwarcu** [comment]
Current gulp file:

> var angularProtractor = require('gulp-angular-protractor');
> var gulp = require('gulp');
> gulp.task('test', function (callback) {
>     gulp
>         .src(['./specs/**/*.js'])
>         .pipe(angularProtractor({
>             'configFile': 'tco-conf.js',
>             'autoStartStopServer': false
>         }))
>         .on('error', function (e) {
>             console.log(e);
>         })
>         .on('end', callback);
> 
> });
>

**Comment by schwarcu** [comment]
Also, I used to run protractor with parameters like:
protractor tco-conf.js --params.login.user "USERNAME" --params.login.password "PASSWORD"

how do I run protractor with gulp with such parameters?

**Comment by schwarcu** [comment]
Another issue: even if I define specs in gulp file, chrome opens but it doesn't go to any page, it doesn't execute any specs. I mean the browser itself.
![capture](https://user-images.githubusercontent.com/31127747/30202323-53a9677c-947e-11e7-9f83-4ca33accdcef.PNG)

**Comment by rochejul** [comment]
Such as the gulp-protractor plugin, the specs property from the protractor config is ignored. So you should change the scope into your gulp file

For your blank page, it could be an issue with proxies or security environments. Check the protractor configuration to set up this point

Regards

**Comment by rochejul** [comment]
For security configuration, see https://github.com/angular/protractor/issues/124

**Comment by schwarcu** [comment]
I figured out blank page was caused by params not found. I passed parameters as args in gulp configuration.
It all works now.
Tho one question remains: what if I want to define 2 suites with separate sets of test cases? How do I put them in the gulp file? You said protractor specs are ignored

**Comment by rochejul** [comment]
That means you should declare two suites of tests (and so two gulp task)

Example:
````javascript
/*jshint node: true, camelcase: false*/
/*global require: true*/

'use strict';

var gulp = require('gulp');
var gulpProtractorAngular = require('gulp-angular-protractor');

function setupProctator(specs, callback) {
	gulp
        .src(specs)
        .pipe(gulpProtractorAngular({
            'configFile': 'protractor.conf.js',
            'debug': false,
            'autoStartStopServer': true
        }))
        .on('error', function(e) {
            console.log(e);
        })
        .on('end', callback);
}

// Setting up the test task
gulp.task('protractor', function(callback) {
	setupProctator(['**/*.spec.js'], callback);
});

gulp.task('protractor:restricted', function(callback) {
	setupProctator(['example.spec.js'], callback);
});
````

Many thanks
