### ISSUE TITLE
webdriver update fail on clean environment with autoStartStopServer set to false

### ISSUE THREAD

**Issue by Przemyslaw-Marchewka** [rochejul/gulp-angular-protractor#48]
Configuration:

gulpProtractorAngular({
      'configFile': 'protractor-config.js',
      'debug': false,
      'autoStartStopServer': false,
      'webDriverUpdate': false,
      'webDriverUpdate.skip': true
    })

Error message:
[15:30:10] E/local - Error code: 135
[15:30:10] E/local - Error message: No update-config.json found. Run 'webdriver-manager update' to download bi
naries.
[15:30:10] E/local - Error: No update-config.json found. Run 'webdriver-manager update' to download binaries.

WORKAROUND:
If you set  autoStartStopServer to true and than to false it is ok

**Comment by rochejul** [comment]
Hi

I am not sure to understand: do you run twice the plugin ?
Could you provide a tiny project to illustrate your issue please ?

Many thanks

**Comment by Przemyslaw-Marchewka** [comment]
You need to run it on a clean environment with autoStartStopServer: false. 
Plugin is trying to execute webdriver-manager update but it fails.

**Comment by rochejul** [comment]
Close to insufficient information and no sample project to illustrate the issue
