### ISSUE TITLE
teapot error on vinyl@406

### ISSUE THREAD

**Issue by shareef84** [rochejul/gulp-angular-protractor#49]
I constantly see teapot error on vinyl package which as pointed out by network administrator has caused by shrinkwrapped packages. any recommendation on this or any plan to remove npm-shrinkwrap in near future? appreciate your help.

**Comment by rochejul** [comment]
Hi
Even if we remove the shrinkwrap file, you could have this error, because there is no wildcard version assocatied on the dependecy which use vinyl, which is gulp-util.

Maybe we could migrate to gulp-util@3.0.8 which uses vinyl at least 0.5.0.

Or don't use anymore gulp-util (which is deprecated): https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by shareef84** [comment]
Thank You! I think I understand the solution.  Do you think package-lock.json would be a better solution? 

Problem my team as such is we use enterprise repo for plugin management not public npmjs repository. JFrog entreprise repository doesn't support shrink wrapped packages and causes our build to fail.

**Comment by rochejul** [comment]
Package-lock.json files are generated if there is no skrinkwrap file (this is the same format). So it cannot resolve the issue sadly.

I try to update the dependency as soon as possible

**Comment by shareef84** [comment]
thanks again. I will wait for the update.

**Comment by rochejul** [comment]
gulp-utils seems to be used only for logging. And so could be replace with https://www.npmjs.com/package/fancy-log

**Comment by rochejul** [comment]
And we have to use too https://www.npmjs.com/package/plugin-error

**Comment by rochejul** [comment]
Release 1.2.0 done

**Comment by shareef84** [comment]
thanks! I pulled latest version and it worked like a charm. I appreciate your help
