### ISSUE TITLE
Protractor doesn't continue on verification selenium

### ISSUE THREAD

**Issue by riemers** [rochejul/gulp-angular-protractor#5]
I think there might be an issue with that, if not then please let me know.

In node_modules/gulp-angular-protractor/web-driver.js there is a check on selenium to find the string "jetty" but as of 2.46 i believe this is no longer called jetty but "Selenium Server is up and running" on the older version this string was "Started org.openqa.jetty.jetty.Server". I see a similar issue being fixed the same way https://github.com/nightwatchjs/nightwatch/commit/d1495b02e283801139211d62a3e4446504933364

**Comment by rochejul** [comment]
Hi @riemers 

Which version of gulp-angular-protractor do you use ?

Because I remember a similar issue. Look to this pull-request: https://github.com/rochejul/gulp-angular-protractor/pull/1

I suggest you use the 0.0.6 version

Cheers

**Comment by riemers** [comment]
Ah, i see the same kind of fix. I assumed my gulp setup would take the latest version. But in this particular fix i see that the text is now changed to Selenium server is up. That means backwards compatible with older versions of selenium will not work. So correct check might be to do both checks. But i can work from this. Feel free to close if you don't see a need for both.

**Comment by rochejul** [comment]
Both were manager on the version 0.0.4:https://github.com/rochejul/gulp-angular-protractor/commit/024973ca3f605e85d310d3de84968452d752d570

I will close the issue. If you still have problems please reply to this issue and I will open it again.

Cheers

**Comment by riemers** [comment]
I see, sorry for the troubles. Found this issue with someone using it, should have looked at the code online more.
