### ISSUE TITLE
More than one config file is specified error

### ISSUE THREAD

**Issue by DBaker85** [rochejul/gulp-angular-protractor#7]
Hello,

I am currently trying to integrate this into a test suite. The aim is to have a front end that allows the user to launch a request is to the server, the tests are then launched and the front-end is updated.

This front end allows to launch the test a couple of times if wanted.

Here is my code : 

``` node
var testSuite = function(){
  gulp
      .src(['./test/testcases/*.js'])
      .pipe(gulpProtractorAngular({
         'configFile': './test/config/conf.js',
          'debug': false,
          'autoStartStopServer': true,
          'isVerbose': true,
      }))
}
```

``` node
app.post('/results', function (req, res) {
  if (req.body.test === 'start') {
    testSuite();
  }
});
```

This works perfectly the first time launched, but if it is launched a second time, I get this error message:

``` shell
Usage: protractor [configFile] [options]
configFile defaults to protractor.conf.js
The [options] object will override values from the config file.
Error: more than one config file specified
```

**Comment by rochejul** [comment]
Hi,

Can you give me more feedbacks around your issue, like:
- NodeJs / NPM versions
- OS version
- gulp-angular-protractor version

If possible, can you give me a project example with your configuration ?

Many thanks

**Comment by DBaker85** [comment]
So, 
- Npm 3.5.2
- Node 4.2.4
- Windows 7 pro sp1
- gulp protractor angular 0.0.6
- protractor 3.0.0

Here are the files I can send you, I had to add them as txt files but they are still readable

[app.js](https://github.com/rochejul/gulp-angular-protractor/files/98739/app.txt)
[conf.js](https://github.com/rochejul/gulp-angular-protractor/files/98740/conf.txt)

**Comment by DBaker85** [comment]
I was going through the files from your end, but could it be this?

gulp-stream.js
Line 47.

``` node
 // Pass in the config file
 args.unshift(options.configFile);
```

Could it be that because the process is not ending like a gulp task would, the config is still populated and relaunching the task pushes a second config file into the array?

**Comment by rochejul** [comment]
Have you some space into your path to your project ?
If so, maybe this is an issue with the protractor cli interface, which thinks there are many config file specified

**Comment by DBaker85** [comment]
So my guess was correct, the task was not terminating so the config file was re populated.I did not solve this issue, but I got around it by launching a gulp-protractor task as a child process. The task exits normally and there are no more issues.

Thanks for your time.
