### ISSUE TITLE
Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by karneaud** [rochejul/gulp-angular-protractor#9]
using your plugin to run some e2e tests and got the following error running the gulp task

> [20:04:01] gulp-angular-protractor - Webdriver standalone will be updated
> selenium standalone is up to date.
> chromedriver is up to date.
> [20:04:01] gulp-angular-protractor - Webdriver standalone is updated
> [20:04:01] gulp-angular-protractor - Webdriver standalone server will be started
> internal/child_process.js:298
>     throw errnoException(err, 'spawn');
>     ^
> 
> Error: spawn ENOTDIR
>     at exports._errnoException (util.js:856:11)
>     at ChildProcess.spawn (internal/child_process.js:298:11)
>     at Object.exports.spawn (child_process.js:367:9)
>     at Object.module.exports.webDriverStandaloneStart (/Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt-lumen-dingo/public/node_modules/gulp-angular-protractor/gulp-angular-protractor/web-driver.js:116:36)
>     at ChildProcess.<anonymous> (/Users/kendallarneaud/Documents/Git/heroku/aurasma-treasure-hunt-lumen-dingo/public/node_modules/gulp-angular-protractor/gulp-angular-protractor/web-driver.js:176:18)
>     at ChildProcess.g (events.js:273:16)
>     at emitTwo (events.js:100:13)
>     at ChildProcess.emit (events.js:185:7)
>     at maybeClose (internal/child_process.js:827:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by rochejul** [comment]
Hi @karneaud 

Can you give please:
- The configuration of the protractor tests
- The configuration of the gulp task
- The NPM / Node version
- Your system version

The error tolds that the targeted file is not a directory, but I would like more detail to understand why.

Many thanks

**Comment by karneaud** [comment]
protractor.conf....

```
{

  allScriptsTimeout: 11000,

  baseUrl: 'http://localhost:' + gulpConfig.testPort,

  capabilities: {
    browserName: 'chrome',
    'tunnel-identifier': process.env.TRAVIS_JOB_NUMBER,
    build: process.env.TRAVIS_BUILD_NUMBER,
    name: 'Protractor Tests'
  },

  framework: 'jasmine2',

  jasmineNodeOpts: {
    isVerbose: true,
    showColors: true,
    includeStackTrace: true,
    defaultTimeoutInterval: 30000,
    print: console.log
  },

  specs: [
    'e2e/**/*.js'
  ],
  directConnect: true,

  sauceUser: process.env.SAUCE_USERNAME,

  sauceKey: process.env.SAUCE_ACCESS_KEY

}
```

gulp task

```
gulp.task('protractor', ['prod','webdriver_manager',  'webdriver'], function(cb) {

  const testFiles = gulp.src('test/e2e/**/*.js');

  testServer({
    port: config.testPort,
    dir: config.buildDir
  }).then((server) => {
    console.log('ok server up');
    testFiles.pipe(protractor({
        configFile: config.test.protractor,
        args: ['--baseUrl', config.baseUrl],
        debug:true
    })).on('error', (err) => {
      // Make sure failed tests cause gulp to exit non-zero
      throw err;
    }).on('end', () => server.close(cb));
  });

});
```

Node version **5.7.1**

System is **Mac OS El Capitan**
